apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mywebapp
  name: mywebapp
spec:
  containers:
  - image: hariharan410/webapp
    name: mywebapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}