- name: Installing Python
  hosts: all
  become: yes
  tasks:
      - name: Install python3 & apache2 on Ubuntu
        apt:
            name:
            - python3
            - apache2
            state: present
        when: ansible_os_family == "Debian"

      - name: Install python3 & httpd on RedHat
        yum:
            name:
            - python3
            - httpd
            state: present
        when: ansible_os_family == "RedHat"

      - name: Install python3 in SUSE
        zypper:
          name: python3
          state: present
        when: ansible_os_family == "Suse"